### ISSUE TITLE
Research & Document Trace Together

### ISSUE THREAD

**Issue by RoyMurphy** [RoyMurphy/Veribit#19]
We need to research and document the viability of helping and integrating with Trace Together https://www.tracetogether.gov.sg/ as an urgent integrated partnership. Any plans of action, ideas, documentation etc can be listed here publically to help with the Covid-19 pandemic in any way possible. As soon as the codebase is made public, we should fork it and see how we can help, partner, integrate and distribute. All ideas are on the table, so please share.

**Comment by RoyMurphy** [comment]
Projects: 
https://www.tracetogether.gov.sg/
https://bluetrace.io/

**Comment by dipzz13** [comment]
Hello. we are interested in implementing this in Nepal. Our Government has been attempting to conduct contact tracing manually (cold-calls), which has proven to be ineffective and inefficient so far. We would like to build an app quite similar to TraceTogether.

- What can we do to  prepare integration and distribution of the system? 
- When can we expect the open source code to be available?

**Comment by brgormz** [comment]
I am also interested in application of this in the U.S...and appreciate any pointers on where/when the SG project has a public repo!

**Comment by mtskvch** [comment]
Hello
we are interested in localisation this app for users in Russia. 

And I waiting info about TraceTogether/Blue trace public repo and documentation. I would be grateful for any information.

**Comment by RoyMurphy** [comment]
Thank you both. Yes, we are keeping an eye out for the codebase release and any update or changes will appear here.

**Comment by tastrax** [comment]
Is this what you are after? https://github.com/OpenTrace-community

**Comment by RoyMurphy** [comment]
Yes, thank you. After researching further, it turns out that only governement approved companies can release such apps on either Apple Store or Google Play, as per their terms and conditions.
