### ISSUE TITLE
#3 Image obfuscation

### ISSUE THREAD

**Issue by RoyMurphy** [RoyMurphy/Veribit#3]
*This enhancement has a bounty of 2 BSV

Due to passport/credit card details being stored on Bitcoin's immutable public blockchain, we need to prevent this sensitive data from being human readable. Therefore, we need a way of cryptographically building the image in the user's window via some form of cryptographic method from the uploaded txid.
Ideally, I would like to embed the Shamir Secret Sharing split key thresholding algorithm from nChain, if available. I may yet have to pitch this idea if it's not currently publically available.
Failing that, we need to find at best an ECDSA file encrypter, worst case some kind of pseudo-random PGP key generator assigned to each user.
I will pay a double bounty of 4 BSV for a successful Shamir Secret Sharing solution.

**Comment by shade** [comment]
Is this still up for grabs?

**Comment by RoyMurphy** [comment]
Yes, this is still up for grabs.
The Nakasendo SDK is now live for SSS Threshold Signatures.
https://nakasendoproject.org/

**Comment by RoyMurphy** [comment]
Done.
